$schema: "http://json-schema.org/draft-07/schema#"
description: snakemake configuration file 
properties:
  genome_filename:
    type: string
    description: filename for genome (in fasta format), e.g. 'GCF_000001635.27_GRCm39_genomic.fna'
  annotation_filename:
    type: string
    description: filename for annotation (in GTF format), e.g. 'GCF_000001635.27_GRCm39_genomic.gtf'
  genome_name:
    type: string
    description: used for labeling genome index files
  seqtype:
    type: string
    description: Experiment type. One of 'rnaseq' or 'temposeq'
  mode:
    type: string
    description: Sequencing mode. One of 'se' (single-end) or 'pe' (paired-end)
  threads:
    type: integer
    default: 1
    description: Number of threads to use, for multi-threaded programs (default 1)
  qc:
    projectdir:
      type: string
      description: e.g "~/path/to/project" Use when loading. Can also hard code if for some reason you need that
    project_name:
      type: string
      description: Change depending on your project name
    clust_method:
      type: string
      description: For clustering. Options are "spearman" or "pearson"
    tree_height_cutoff:
      type: number
      description: For clustering
    dendro_color_by:
      type: string
      description: Specify how you would like to color the dendrograms
    nmr_threshold:
      type: integer
      description: 10% of 1M reads for TempOSeq = 100,000; 10% of 10M reads for RNA-Seq = 1,000,000.
    align_threshold:
      type: number
      description: 0.5 (50%) alignment rate for TempO-Seq Experiments
    gini_cutoff:
      type: number
      description: Samples with Gini coefficients > cutoff are removed from the analysis.
    sampledata_sep:
      type: string
      description: Comma for TempO-Seq, Maybe tabs for RNASeq, customize!
    groups:
      type: object
      properties:
        one:
          type: array
          items:
            type:
              string
        two:
          type: array
          items:
            type:
              string
        three:
          type: array
          items:
            type:
              string
        four:
          type: array
          items:
            type:
              string
        five:
          type: array
          items:
            type:
              string
        six:
          type: array
          items:
            type:
              string
    batch_var:
      type: string
      description: If there is are multiple batches in the experiment; otherwise use NULL
    dose:
      type: string
      description: If there is a dose in the experiment; otherwise use NULL
    treatment_var:
      type: string
      description: Treatment variable
    platform:
      type: string
      description: TempO-Seq Or RNA-Seq
    collapse_replicates: 
      type: boolean
      description: Set to true if you have replicate flow cells that need to be summed into a single value, false otherwise
    technical_control:
      type: string
      description: Column names for metadata, if applicable
    reference_rna:
      type: string
      description: Column names for metadata, if applicable
    solvent_control:
      type: string
      description: Column names for metadata, if applicable
  DESeq2:
    projectdir:
      type: string
      description: e.g "~/path/to/project" Use when loading. Can also hard code if for some reason you need that
    project_name:
      type: string
      description: Change depending on your project name    species: "human"                 # one of human, mouse, rat, hamster
    design:
      type: string
      description: e.g., "group", single experimental group of interest; entries in this column must match the contrast names.
    intgroup:
      type: string
      description: e.g., ["group"], experimental group of interest plus covariates; can be more than one
    nuisance:
      type:string
      description: e.g., "Batch", use to remove batch effects for PCA/Heatmaps visualiziations
    flag:
      type: boolean
      descrption: Runs all analysis by default when set to TRUE
    platform:
      type: string
      description: One of RNA-Seq or TempO-Seq
    group_facet:
      type: string
      description: e.g., "chemical", If you have many different experimental groups, you may subset the report by specifying a column in the metadata to filter groups, and then setting the group of interest in group_filter
    group_filter:
      type: string
      description: Which group (within the column chosen for group facet) will this report be done on?
    sortcol:
      type: string
      descrption: e.g., "dose", Optionally, a column by which to sort the contrasts
    strict_contrasts:
      type: boolean
      description: If TRUE, use both columns (exp, cont) of contrasts file to limit what is included in the report. Default should usually be FALSE.
    exclude_samples:
      type: string
      description: Optionally, a vector of sample names to exclude from the analysis
    exclude_groups:
      type: string 
      description: Optionally, a vector of groups to exclude from the analysis. By default this is assumed to be in the column specified by the "design" parameter.
    include_only_column:
      type: string
      description: Restrict analysis to group(s) in the column listed here based on params$include_only_group.
    include_only_group:
      type: string
      description: Restrict analysis to this/these group(s) within the column listed in params$include_only_column
    use_cached_RData:
      type: boolean
      description: If possible, load the saved RData for dds object and gene IDs
    cpus:
      type: integer
      description: Set to a lower number (e.g., 2 to 4) if you aren't working in a server environment
    run_pathway_analysis:
      type: boolean
      description: Optionally disable pathway analysis if not available for your organism
    wikipathways_directory:
      type: string
      description: e.g., "~/shared/dbs/wikipathways", where your WikiPathways GMT files are found
    biospyder_dbs:
      type: string
      description: e.g., "~/shared/dbs/biospyder/", where your biospyder manifest files are found
    nBestFeatures:
      type: integer
      description: The number of best features to make plots of their counts
    nBest:
      type: integer
      description: Number of features to include in table and limiting PCA/clustering analysis
    nHeatmap:
      type: integer
      description: Number of most variable genes for heatmap
    nHeatmapDEGs:
      type: integer
      description: Number of DEGs for heatmap
    sampledata_sep:
      type: string
      description: e.g., "," Comma for TempO-Seq, Maybe tabs ("\t") for RNASeq, customize!

required:
  - genome_filename
  - annotation_filename
  - genome_name
  - seqtype
  - mode
