# This workflow is used for testing whether the DEG list produced by the new code is identical to the expected result based on example data.

name: Tests

on:
  push:
    branches:
      - '*'
  
  schedule:
    - cron: '0 0 1 * *'
env:
  CACHE_NUMBER: 0

permissions:
  contents: read

jobs:
  build:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        include: 
          - os: ubuntu-20.04
            label: linux-64
            prefix: /usr/share/miniconda3/envs/R-ODAF
        r-version: ['4.1.1']
        python-version: ['3.7']
        seq_type: ['temposeq'] # add later... , 'rnaseq']
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - name: Install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcairo2-dev
          sudo apt-get install libxt-dev
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: R-ODAF
            use-mamba: true
            python-version: ${{ matrix.python-version }}
            mamba-version: "*"
            auto-activate-base: false
            auto-update-conda: true
            use-only-tar-bz2: true # This needs to be set for caching to work properly, according to others
      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.prefix }}
          key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache
      - name: Update environment
        run: mamba env update -n R-ODAF -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Install extra dependencies
        run: |
          R -e "chooseCRANmirror(1, graphics=FALSE); \
          remotes::install_github('bwlewis/crosstool'); \
          install.packages('cellWise')"
      - name: Check conda install
        run: |
          conda info
          conda list
        shell: bash -l {0}
      - name: Import data
        run: |
          ls -alht # What is in the "working directory"?
          git clone https://github.com/EHSRB-BSRSE-Bioinformatics/test-data
          rm -r data # Remove existing directory before replacing w/ test data
          rm -r config # Remove existing directory before replacing w/ test data
          mv test-data/${{ matrix.seq_type}}/* ./
          wget https://github.com/EHSRB-BSRSE-Bioinformatics/unify_temposeq_manifests/raw/main/output_manifests/Human_S1500_1.2_standardized.csv
          wget https://wikipathways-data.wmcloud.org/20210810/gmt/wikipathways-20210810-gmt-Homo_sapiens.gmt
      - name: Run workflow
        run: |
          snakemake --cores 8
      - name: Render studywide QC
        run: |
          Rscript scripts/render_studywide_QC_report.R
      - name: Run DESeq2
        run: |
          Rscript scripts/run_DESeq2.R
      - name: Render Reports
        run: |
          Rscript scripts/render_DESeq2_report.R
