# This workflow is used for testing whether the DEG list produced by the new code is identical to the expected result based on example data.

name: Tests

on:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        r-version: ['4.1.1']
        python-version: ['3.7']

    steps:
      - uses: actions/checkout@v3
      - name: Install linux dependencies
        run: |
          sudo apt update
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up miniconda
      - uses: actions/checkout@v2
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: R-ODAF
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          auto-activate-base: false
          auto-update-conda: true
          use-only-tar-bz2: true # This needs to be set for caching to work properly, according to others
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install R dependencies
        run: |
          source("install.R")
        shell: Rscript {0}
      - name: Snakemake tests
        run: |
          conda activate R-ODAF
